### PR TITLE
fix: results vertical ordering w.r.t active tab

### LINKED ISSUE #78: fix: showing results for respective tab
**Problem**
Right now even if we have switched to the isochrones tab, we are still showing results of the directions tab at the bottom. After entering name of a place for which we want to generate an isochrone we don't know that the results are at the bottom of the sidebar below the results of directions. This is not very convenient for users.

**Solution**
We can show the results depending upon the respective tab that has been chosen.     

**Screenshot**
https://user-images.githubusercontent.com/55504616/222498026-b86acf99-0f28-4403-99b5-9ac2c6541818.mp4

**Additional note**
I can work on this.

### PR DESCRIPTION
**Pull request by Ananya2001-an**
**Fixes issue**
closes #78 

With respect to the active tab we are showing results at the bottom in the respective order.

**Screenshot**
https://www.awesomescreenshot.com/video/15283492?key=f6d41803f4749982e1d2c825d8131e03

### CODE REVIEW

**Comment by Ananya2001-an** [comment]
@nilsnolde kindly review the changes.

**Review by nilsnolde — COMMENTED** [review]
Looks good I think. I'll review (and try out) all PRs this weekend hopefully.

**Comment by Ananya2001-an** [comment]
> Looks good I think. I'll review (and try out) all PRs this weekend hopefully.

Cool!

File: src/Controls/index.jsx [hunk 1]
```diff
@@ -219,8 +219,17 @@ class MainControl extends React.Component {
                 <ServiceTabs />
               </div>
             </Segment>
-            <DirectionOutputControl />
-            <IsochronesOutputControl />
+            {(activeTab === 0 && (
```
Comment (nilsnolde) [inline src/Controls/index.jsx:222]: should we add a comment why we did this? it does seem weird on the first glance when you switch tabs around, that the order switches. but in the end we do it because apparently on small screens it's not showing both.

Comment (Ananya2001-an) [reply src/Controls/index.jsx:222]: Yeah I guess we can add a comment but what exactly should be written? I am not sure what to write in one simple sentence to explain this.

Comment (nilsnolde) [reply src/Controls/index.jsx:222]: I think this is ok enough: `because apparently on small screens it's not showing both`, maybe plus `, so we switch the order on tab switch`

Comment (Ananya2001-an) [reply src/Controls/index.jsx:222]: Okay I will add this comment soon.

**Comment by Ananya2001-an** [comment]
Hey @nilsnolde I have added the comment. I guess you can merge it now.

File: src/Controls/index.jsx [hunk 2]
```diff
@@ -219,8 +219,18 @@ class MainControl extends React.Component {
                 <ServiceTabs />
               </div>
             </Segment>
-            <DirectionOutputControl />
-            <IsochronesOutputControl />
+            {/* because apparently on small screens it's not showing both, so we switch the order on tab switch */}
```
Comment (nilsnolde) [inline src/Controls/index.jsx:222]: sorry for being nitpicky on this, but: can you use `//` line comments for single comments and `/* */` multiline comments for more elaborate ones? Also, move the comment above the `{` on its own line. I'm surprised `prettier` doesn't complain..

Comment (nilsnolde) [reply src/Controls/index.jsx:222]: Oh I see, is this somehow related to being inside the React "HTML" stuff? I see the enclosing `{}` and wonder why they're there. Then the way you did it, might be the only valid way to comment in this situation?

Comment (Ananya2001-an) [reply src/Controls/index.jsx:222]: Yeah comments in JSX are supposed to be this way.
